FROM openjdk
WORKDIR user/lib
ADD ./target/Favourite-List-Service-0.0.1-SNAPSHOT.jar /user/lib/Favourite-List-Service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","Favourite-List-Service-0.0.1-SNAPSHOT.jar"]
